# Generated by Django 5.0.3 on 2024-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('polling_station', models.IntegerField()),
                ('gmen', models.IntegerField()),
                ('gwomen', models.IntegerField()),
                ('gthird', models.IntegerField()),
                ('gtotal', models.IntegerField()),
                ('omen', models.IntegerField()),
                ('owomen', models.IntegerField()),
                ('othird', models.IntegerField()),
                ('ototal', models.IntegerField()),
                ('smen', models.IntegerField()),
                ('swomen', models.IntegerField()),
                ('stotal', models.IntegerField()),
                ('overall_total', models.IntegerField()),
            ],
        ),
    ]
