# Generated by Django 5.0.3 on 2024-04-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100)),
                ('no', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('electors', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('turnout', models.FloatField()),
                ('margin', models.IntegerField()),
                ('margin_percentage', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
